version: 2.1

jobs:
  build:
    working_directory: ~/circleci-java
    docker:
      - image: "cimg/openjdk:18.0.1"
    steps:
      - checkout
      - run: |
         echo "pipeline ID -> $CI_PIPELINE_ID"
         echo "job ID -> $CI_PIPELINE_IID"
         echo "build version -> $BUILD_VERSION"
         echo "project name -> $CI_PROJECT_NAME"
         mvn clean package -DskipTests
         echo 'build completed.....' 
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/openjdk:18.0.1"
    steps:
      - checkout
      - run: mvn test 

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build