version: 2.1

jobs:
  build:
    working_directory: ~/circleci-java
    docker:
      - image: "cimg/openjdk:18.0.1"
    steps:
      - checkout
      - run: |
          mvn clean package -DskipTests
          echo 'build completed.....' 
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/openjdk:18.0.1"
    steps:
      - checkout
      - run: mvn test 

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build